<?php
namespace WebApp\components;

class PaintType
{
    static $data = [
        [
            'type' => 'Lama',
            'category' => 'Interior',
            'primer' => 'KANSAI MASONRY SEALER',
            'rate' => 10,
            'package' => [2.5, 20],
            'topcoat' => 'KANSAI ECO CLEAN',
            'topcoat_rate' => 13,
            'topcoat_package' => [2.5, 20],
        ],
        [
            'type' => 'Lama',
            'category' => 'Interior',
            'primer' => 'HI-SEALER',
            'rate' => 9,
            'package' => [4, 20],
            'topcoat' => 'KANSAI ANTI-MOSQUITO',
            'topcoat_rate' => 10,
            'topcoat_package' => [2.5, 20],
        ],
        [
            'type' => 'Lama',
            'category' => 'Interior',
            'primer' => 'HI-SEALER',
            'rate' => 9,
            'package' => [4, 20],
            'topcoat' => 'KANSAI PROPERTY INTERIOR',
            'topcoat_rate' => 8,
            'topcoat_package' => [5, 25],
        ],
        [
            'type' => 'Lama',
            'category' => 'Interior',
            'primer' => 'HI-SEALER',
            'rate' => 9,
            'package' => [4, 20],
            'topcoat' => 'KANSAI TROPIC',
            'topcoat_rate' => 7,
            'topcoat_package' => [5, 20],
        ],
        [
            'type' => 'Lama',
            'category' => 'Exterior',
            'primer' => 'KANSAI MASONRY SEALER',
            'rate' => 10,
            'package' => [2.5, 20],
            'topcoat' => 'KANSAI SPLESH',
            'topcoat_rate' => 13,
            'topcoat_package' => [2.5, 20],
        ],
        [
            'type' => 'Lama',
            'category' => 'Exterior',
            'primer' => 'HI-SEALER',
            'rate' => 9,
            'package' => [4, 20],
            'topcoat' => 'PROPERTY Eksterior',
            'topcoat_rate' => 9,
            'topcoat_package' => [5, 25],
        ],
        [
            'type' => 'Baru',
            'category' => 'Interior',
            'primer' => 'KANSAI ALKALI PRIMER',
            'rate' => 9,
            'package' => [2.5, 20],
            'topcoat' => 'KANSAI ECO CLEAN',
            'topcoat_rate' => 13,
            'topcoat_package' => [2.5, 20],
        ],
        [
            'type' => 'Baru',
            'category' => 'Interior',
            'primer' => 'HI-SEALER',
            'rate' => 9,
            'package' => [4, 20],
            'topcoat' => 'KANSAI ANTI-MOSQUITO',
            'topcoat_rate' => 10,
            'topcoat_package' => [2.5, 20],
        ],
        [
            'type' => 'Baru',
            'category' => 'Interior',
            'primer' => 'HI-SEALER',
            'rate' => 9,
            'package' => [4, 20],
            'topcoat' => 'KANSAI PROPERTY INTERIOR',
            'topcoat_rate' => 8,
            'topcoat_package' => [5, 25],
        ],
        [
            'type' => 'Baru',
            'category' => 'Interior',
            'primer' => 'HI-SEALER',
            'rate' => 9,
            'package' => [4, 20],
            'topcoat' => 'KANSAI TROPIC',
            'topcoat_rate' => 7,
            'topcoat_package' => [5, 20],
        ],
        [
            'type' => 'Baru',
            'category' => 'Exterior',
            'primer' => 'KANSAI ALKALI PRIMER',
            'rate' => 9,
            'package' => [2.5, 20],
            'topcoat' => 'KANSAI SPLESH',
            'topcoat_rate' => 13,
            'topcoat_package' => [2.5, 20],
        ],
        [
            'type' => 'Baru',
            'category' => 'Exterior',
            'primer' => 'HI-SEALER',
            'rate' => 9,
            'package' => [4, 20],
            'topcoat' => 'KANSAI PROPERTY EKSTERIOR',
            'topcoat_rate' => 9,
            'topcoat_package' => [5, 25],
        ],
        [
            'type' => 'KayuBesi',
            'category' => 'KayuBesi',
            'primer' => '',
            'rate' => 0,
            'package' => [],
            'topcoat' => 'KANSAI FTALIT',
            'topcoat_rate' => 12,
            'topcoat_package' => [1, 5, 20],
        ],
        [
            'type' => 'KayuBesi',
            'category' => 'KayuBesi',
            'primer' => '',
            'rate' => 0,
            'package' => [],
            'topcoat' => 'KANSAI FTALIT DUO',
            'topcoat_rate' => 12,
            'topcoat_package' => [0.9],
        ],
        [
            'type' => 'KayuBesi',
            'category' => 'KayuBesi',
            'primer' => '',
            'rate' => 0,
            'package' => [],
            'topcoat' => 'KANSAI PROPERTY Glozz',
            'topcoat_rate' => 10,
            'topcoat_package' => [0.8],
        ],
    ];
}
